server:
  port: 8083
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

#    lease-expiration-duration-in-seconds: 10
#    lease-renewal-interval-in-seconds: 5
#指定当前服务为client
  client:
  #配置注册中心的url地址
    serviceUrl:
#      defaultZone: http://localhost:8888/eureka/
      defaultZone: http://47.95.253.137:8888/eureka/
spring:
#配置当前服务名，服务与服务之间的相互调用依据就是用服务名来标识的
  application:
    name: service-c1


    #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
    #注意，EurekaServer一定要设置eureka.server.eviction-interval-timer-in-ms否则这个配置无效，这个配置一般为服务刷新时间配置的三倍
    #默认90s
#    eureka.instance.lease-expiration-duration-in-seconds=15
    #服务刷新时间配置，每隔这个时间会主动心跳一次
    #默认30s
#    eureka.instance.lease-renewal-interval-in-seconds=5
